=== PalaciosDigital/scraper-cortes-luz/schema/cortes_luz.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Registro de corte de luz programado",
  "type": "object",
  "required": ["provincia", "canton", "alimentador", "fecha", "dia", "horario",
               "tipo_trabajo", "zona_cortes", "sectores"],
  "properties": {
    "provincia":    {"type": "string", "minLength": 2},
    "canton":       {"type": "string", "minLength": 2},
    "alimentador":  {"type": "string"},
    "fecha":        {"type": "string", "pattern": "^\\d{4}-\\d{2}-\\d{2}$"},
    "dia":          {"enum": ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]},
    "horario":      {"type": "string", "pattern": "^\\d{2}:\\d{2} a \\d{2}:\\d{2}$"},
    "tipo_trabajo": {"type": "string"},
    "zona_cortes":  {"type": "string"},
    "sectores":     {"type": "string", "minLength": 2},

    "cantones":           {"type": "array", "items": {"type": "string"}, "minItems": 1},
    "provincia_original": {"type": "string"},
    "distribuidora":      {"type": "string"}
  },
  "additionalProperties": false
}

=== PalaciosDigital/scraper-cortes-luz/data/vigilancia/registros/9466657ae12d45d9985be9dea6e37b37a4ba5d31803fd9db4b7911bf7266bd8e.json
[{"provincia": "SUCUMBIOS", "canton": "Lago Agrio", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "INSTALACIÓN DE INFRAESTRUCTURA ELÉCTRICA", "zona_cortes": "", "sectores": "Las Palmeras, Mariscal Sucre, 11 de Abril, Eloy Alfaro, San Francisco, Nueva Esperanza, El Dorado, Gilson Toledo, Mendieta Falcones Milton Marcos, San Valentin, Nuevo Paraiso, 25 de Diciembre, Las Delicias, Vista Hermosa, Subdivisión Alejandrina Pineda, Segundo Orellana, B, Villaflora, Mirador, Ierac, Del Chofer, Los Almendros, Lot Gonzales, 9 de Octubre, Perla del Oriente, Unión y Progreso, Lot. Luis Salazar, 24 de Julio, Plan Velasco Ibarra, av. 20 de Junio, VConsejo provincial, CNE, CNEL, Consejo de la Judicatura, Ofc, IESS, Parque de la Madre- Rcnto. Perla, Lot Cesar Mena, Lot. Nuevos Hermanos, Lot, Mario Guerrero, Lot, El Jardin, Lot. Mario Guerrero, B. La Floresta, Lot, Nuevo Cariamanga, B. San antonio, Lot. Las Heliconias, Rcnto. Santa Rosa, B, San Miguel, B. La Victoria, B. Santa. Marianita, Santa Cruz, Pre Coop, San Isidro, Pre Coop. Bella Esperanza, Pre Coop Alma Lojana, Rcto. Bella Vista, Pre Coop Recuerdos del Oriente, Pre Coop. 3 Palmas, Sub, Grefa Juan Miguel, Pre Coop. Agropecuaria Cafetalera San Miguel, Rcto, Patria Nueva, Proyecto San Miguel, Pre Coop 10 de Agosto, Santa Marianita, Barrios de General Farfan, Nuevo Mundo, CEBAB. Puente Internacional, Pre Coop, Isidro Ayora, Monterrey, Puerto Camacho, Alma Lojana, Rcto, 5 de Agosto, Nueva Vicentina, Corazón Orense, Pre Coop Río Puno. Luis Bermeo, Pre Coop. Brisas de San Miguel, 18 de Noviembre, Pre Coop Chananga, 24 de Julio, Trampolin del Triunfo, La Charapa, 9 de Marzo, Valle Hermoso, Monterrey, Rey Selva, Flor de Chone 1 y 2, Flores del Oriente, La victoria, Heliconias Amazonicas, B, San Antonio, la Floresta, Sub. Manzano, San Miguel, Buena Fé, Gilson Toledo,- Rcto. La Laguna, Rcnto, La Perla, Puerto ecuador, Rcnto. 23 de Marzo Coop. San Vicente, Puerto Ecuador, Perla del Pacífico, Castillo quevedo Georgina Teresa, Lot. Lago Avanza, San Vicente, Pre Coop Perla del Pacífico, Puerto ecuador, Brisas del Oriente, Pre Coop 10 de Agosto, Pre Coop Nuevo Mundo, Pre Coop Isidro Ayora, Recinto San Andres, Sultana de Oro, El Condor, Reina del Cisne, pre Coop 5 de Marzo. Recinto Salinas, Fronteras del Oriente, Pre Coop Cochas del Betano, Jehova es mi Pastor, Unión campesina, Pre Coop. Orellana, Riveras del Oriente, Pre Coop. Imbabura, Rcnto el Porvenir, Juan Yanez, Pre Coop Carchi, B. Los Colorados, Santa Rosa.", "cantones": ["Lago Agrio"], "distribuidora": "CNEL EP"}, {"provincia": "SUMCUMBÍOS", "canton": "Cascales y", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "Gonzao Pizarro TRABAJOS EN LÍNEA DE SUBTRANSMISIÓN", "zona_cortes": "", "sectores": "El centro poblado de Lumbaquí, Vía al cerro de Lumbaquí, El Progreso, Las Parcelas, Piedra Bola, Nuevo Paraíso, El Cisne, Aguas Turbias, Unión Independiente, San Pablo, Unión Bolivarense, Playas del Río Tigre, Playas del Río Coca, Laguna Shiguacocha, Sardinas Guaydaurco, Recinto Los Tanques, Vía a la central Hidroelectrica Lumbaqui - Batallón de apoyo logístico, Aguarico de Lumbaquí, Vía a la Bonita, Flor del Oriente, Flor del Valle, La Amarilla, Chontayacu, El Cabeno, Sinangoe, San Pedro de los Cofanes, Rancho el Encanto, El Chíparo, Puerto Libre, Recodo Bellavista, El Chingual, El Paraíso, La Barquilla, La Pizarra, Los Shyris, La Playa, La Chispa, Duvino, Bermejo, Sector Sur: Puerto Madero, La Troncal, Los Ángeles, San José del Aguarico, Shayari, Playas Seca, El Arenal Dumbiqui, Mushu Kausay, Pachakutik, Ango Bautista, Rcnto. Cubano Jesús del Gran Poder, Cofán Duvuno, Guacamayo, 9 de octubre, 1ro de Mayo, San Andrés, San José, Cascales, Taruca, La Libertad, San Miguel, Allishunko, Cañaveral, Sevilla, San Carlos, Rcnto. El Salvador, Santa Rosa, Barranca Bermeja, San Martín, Providencia, San Pedrito, San Luis, Abdón Calderón Muñoz, Tres Hermanos, Jesús del Gran Poder, Sardinas, Shuar Betano Kichwa, Kichwa Sumak Pampa, Chari.- Vía Lumbaqui ,Reventador, Gonzalo Pizarro, Dashino, Panduyacu, Ruevo Pareiso, Rcnt. Amazonas, Rcnt. Chuscuyacu, Atenas, Rcnto. Chiguapeña, La Delicia, San Francisco, Reventador, Precooperativa Libertad 6 de Octubre, Alma Ecuatoriana, Campamento Reventador, Campamento San Rafael, Flores del Valle. Rcnt. Simón Bolívar.", "cantones": ["Cascales y"], "distribuidora": "CNEL EP"}, {"provincia": "SUMCUMBÍOS", "canton": "Cuyabeno y TIPO DE TRABAJO:", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "Lago Agrio TRABAJOS EN SUBESTACIÓN", "zona_cortes": "", "sectores": "Comunidad San Pablo de Kantesiya, Las Mercedes, Los Ángeles, Perla del Oriente, Precoperativa Tierras Orientales, San José, Tarapoa, Tigre Grande. 3 de Mayo, Aguas Negras, Aleluya, Bella María, Brisas de Cuyabeno, Buena Vista, Campamento Dygoil, Cantagallo, Centro Unión, Comunidad 16 de Abril, Comuna Tase, Cóndor Mirador, Cuyabeno, El Rosario, Equinoccio, Fuerzas Unidas y Las Mercedes, La Calumeña, La Primavera, Las Palmas, Mirian 10, Mirian 4, Puca Peña, Precooperativa 9 de Octubre, Precooperativa Flor de Oro, Precooperativa Paraíso, Precooperativa Simón Bolívar, Sansahuari, Santa Elena, Sinhue, Tigre Playa, Tipishca, Unión Manabita, Unión Nacional, Virgen del Huaico, Voluntad de Dios. 17 de Abril, 3 Palmas, 5 Ases y Sosoranga, Balsareña, Campo Bello, Campamento Jaime Roldós Aguilera, Centro Secoya, Chananga, Chiritza, Chone 1, Chone 2, Comuna Cofán Dureno, Comuna Ñucanchillacta, Comunidad Ñucanchi Llacta, Cooperativa Flor de los Ríos, Cooperativa Pío Jaramillo, Cristóbal Colón, Dureno, El Triunfo, Estación Pichincha, Flor de los Ríos, Fuerza de los Pobres, Golondrinas, Jesús del Gran Poder, La Libertad, La Milagreña, La Y de Harber, Los Diamantes, Los Tapi, Nueva Juventud, Pacayacu, Palma Seca, Parahuaco, Paz y Bien, Playera Oriental, Poza Honda, Precooperativa 1 de Mayo, Precooperativa de Caráquez, Precooperativa Juan Montalvo, Precooperativa Lucha Bolivarense, Precooperativa Los Vergeles, Precooperativa Pionero del Oriente, Precooperativa Quince de Noviembre, Precooperativa San Francisco, Precooperativa San Juan de Pozul, Precooperativa Santa Ana, Precooperativa Santa Rosa, Precooperativa Santa Teresita, Precooperativa Secoya 1, Precooperativa Sol Naciente, Precomerativa 19 de Marzo, Puerto Nuevo, Puerto Sinaí, Rancho Tauro, Real Villa Nueva, Río Pacayacu, San Jacinto, San José de los Ángeles, San Rafael, San Vicente, Shushuqui, Sol de Oriente y Vía Lago, Unión Bolivarense, Unión Lojana, Ucano, Vía Shuara, Plantaciones Ecuatorianas, Vía Tetetes.", "cantones": ["Cuyabeno", "TIPO DE TRABAJO:"], "distribuidora": "CNEL EP"}, {"provincia": "SUMCUMBÍOS", "canton": "Shushufindi", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "TRABAJOS EN SUBESTACIÓN", "zona_cortes": "", "sectores": "Centro de Shushufindi, El Oro, Eloy Alfaro, Integración Social, La Pantera, Precooperativa Horizontes, Río Doch, Tahuantinsuyo, Vía La Pantera. 01 de Mayo, 24 de Mayo, 7 de Julio, El Mirador, El Progreso, El Proyecto, El Rocío, Eno Ande, Estación Shushufindi Norte, Jivino Verde, La Fortuna, La Primavera y Vía al Guanta, Los Laureles, Los Ríos, Los Toritos, Nuevo Paraíso, Parte central de Shushufindi vía Jivino, Poza Honda, Precooperativa Atahualpa, Precooperativa Cumandá, Precooperativa El Sudor, Precooperativa Las Cañitas, Precooperativa Unión de Chone, Precooperativa Valle Hermoso, Puerto Eno, Puerto Santa Rosa, San Antonio, Santa Rosa de Enos, Secoya, Shuaras, Unión Lojana, Unión Paltense, Vía Aguarico 3, Miss Ecuador, Vía Shushufindi hasta el Km 17. 18 de Noviembre, Amazonas, Bella Vista, Comuna 29 de Junio, Comuna Indilama, Comuna Kukush, Comuna Río Jivino, Comuna San Pablo de Kantesiya, Comuna Shariam, Comuna Shuara San Pedro, El Belén, El Carmen, El Triunfo, Israel, Juan Montalvo, Lago San Pablo hasta Puerto Providencia, La Florida, La Magdalena, La Victoria, Limoncocha, Palmeras del Ecuador, Playayacu, Pozo 41, Pompeya, Precooperativa Los Olivos, Puerto Largo, San Antonio, San Francisco de Chicta, San José, San Roque, Nueva Vida, San Vicente, Unidos Venceremos, Yamanunka.", "cantones": ["Shushufindi"], "distribuidora": "CNEL EP"}]

=== PalaciosDigital/scraper-cortes-luz/data/vigilancia/registros/5cb6814c950b01f35ea00e236df5a07539aca999e774738d407c97e5dbe3b909.json
[{"provincia": "MANABÍ", "canton": "Manta", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "INSTALACIÓN DE NUEVAS ESTRUCTURAS", "zona_cortes": "", "sectores": "Barrio la Ensenadita, edificio CNEL, Centro de Manta, Municipio Zona Bancaria, Barrio Jocay Barrio La Victoria, Industrias ALES, Barrio San José, Cementerio de Tarqui, Av. 108, Urbanización MARATEA, Barrio Bellavista #1, Av. 26 desde la calle 7 hasta la calle 20., Barrio La Dolorosa, Barrio Santa Fe, Barrio Santa Mónica, Barrio Los Algarrobos, Colegio Técnico, Parte de la Cdla. Universitaria., Gasolinera Caballo de Troya, Barrio Buenavista.", "cantones": ["Manta"], "distribuidora": "CNEL EP"}, {"provincia": "MANABÍ", "canton": "Portoviejo TRABAJOS EN LÍNEAS DE SUBTRANSMISIÓN", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "", "zona_cortes": "", "sectores": "Av Universitaria, Barrio San Pablo, Cdl El Maestro, Av Reales Tamarindo, Parque Forestal, Vía al Corozo, Cdl Municpal, Solca, Cdl San Marcos, Vía a Crucita hasta el Tomate, Milagro de Río Chico, Cdl Universitari, Parque la Rotonda, UTM, Cdl San José.", "cantones": ["Portoviejo TRABAJOS EN LÍNEAS DE SUBTRANSMISIÓN"], "distribuidora": "CNEL EP"}]

=== PalaciosDigital/scraper-cortes-luz/data/vigilancia/registros/9217106a85b170484e1cef3d6c25c8e4a4cf4a60aab36e6c4454d8c1a1af6bc7.json
[{"provincia": "AZUAY", "canton": "Ponce Enríquez", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "CORRECCIÓN DE PUNTOS CALIENTES CON REAJUSTE DE CONEXIONES", "zona_cortes": "", "sectores": "Todo el cantón Ponce Enríquez.", "cantones": ["Camilo Ponce Enríquez"], "distribuidora": "CNEL EP"}, {"provincia": "EL ORO", "canton": "El Guabo", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "CORRECCIÓN DE PUNTOS CALIENTES CON REAJUSTE DE CONEXIONES", "zona_cortes": "", "sectores": "Todo el cantón El Guabo", "cantones": ["El Guabo"], "distribuidora": "CNEL EP"}, {"provincia": "EL ORO", "canton": "Machala", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "CORRECCIÓN DE PUNTOS CALIENTES CON REAJUSTE DE CONEXIONES", "zona_cortes": "", "sectores": "Todo el cantón Machala.", "cantones": ["Machala"], "distribuidora": "CNEL EP"}, {"provincia": "EL ORO", "canton": "Pasaje", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "CORRECCIÓN DE PUNTOS CALIENTES CON REAJUSTE DE CONEXIONES", "zona_cortes": "", "sectores": "Línea de subtransmisión Peaña – La Iberia", "cantones": ["Pasaje"], "distribuidora": "CNEL EP"}, {"provincia": "GUAYAS", "canton": "Balao", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "CORRECCIÓN DE PUNTOS CALIENTES CON REAJUSTE DE CONEXIONES", "zona_cortes": "", "sectores": "Todo el cantón Balao.", "cantones": ["Balao"], "distribuidora": "CNEL EP"}]

=== PalaciosDigital/scraper-cortes-luz/data/vigilancia/registros/f7b8b63bd2375e76a0d215cadad2e8f927c3907126493a34ec8b7bcbb1e960b4.json
[{"provincia": "ESMERALDAS", "canton": "Esmeraldas", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "Reajuste de elementos, limpieza de aislamiento y cambio de seccionadores en alimentadores de la subestación Las Palmas.", "zona_cortes": "", "sectores": "Norte de la ciudad de Esmeraldas: ECU 911, Tercer Piso, Miramar, El Panecillo, El Regocijo, Mina de Piedra, El Faro, todo el sector de Las Palmas, avenida del Pacífico, canal Telecosta, Hospital Naval, COOPNO, Distrito de Esmeraldas del Servicio Nacional de Aduana, Puerto Pesquero Artesanal, avenida Libertad desde la calle Jr Coronel hasta la calle Lavallen, calle Sucre desde la Jr. Coronel hasta la calle Eugenio Espejo, CNT, Unidad Educativa Liceo Naval, Ciudadela Naval y centro comercial Multiplaza.", "cantones": ["Esmeraldas"], "distribuidora": "CNEL EP"}]

=== PalaciosDigital/scraper-cortes-luz/data/vigilancia/registros/15162ad69a2d177ec1c4131da67e0b91c846fc9f3fa41bd69e3ac9563ff93676.json
[{"provincia": "PICHINCHA", "canton": "Quito", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "MANTENIMIENTO PERIÓDICO", "zona_cortes": "SANGOLQUÍ", "sectores": "VÍA AMAGUAÑA, SAN JUAN, SAN LUIS", "cantones": ["Quito"], "distribuidora": "Ministerio de Ambiente y Energía"}, {"provincia": "PICHINCHA", "canton": "Quito", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "MANTENIMIENTO EMERGENTE", "zona_cortes": "TUMBACO", "sectores": "TUMBACO, EL CHICHE - AV. OSWALDO GUAYASAMÍN", "cantones": ["Quito"], "distribuidora": "Ministerio de Ambiente y Energía"}]

=== PalaciosDigital/scraper-cortes-luz/data/vigilancia/registros/2da45aeded27c171fb63f53664da86eb53fb2e33bc7db7bb37c74bee2ece9c88.json
[{"provincia": "NAPO", "canton": "ARCHIDONA", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "DE AISLADORES EN ESTADO, REEMPLAZO DE EN MAL ESTADO", "zona_cortes": "CANTÓN ARCHIDONA/PARROQUIA ARCHIDONA/HATUN SUMACO-COTUNDO", "sectores": "REEMPLAZO MARGEN IZQUIERDO DE LA VÍA TENA ARCHIDONA MAL DESDE EL CHIMBADERO, BARRIO SAN JACINTO, SECCIONADOR CHAUPISHUNGO, INCHILLAQUI, CÓNDOR MIRADOR, AYAPATA, AGUA MARINA, LA LIBERTAD, SAN AGUSTÍN, ANDALUCIA. SECTORES OESTE DE ARCHIDONA, SINCHI SACHA, CIRCUNVALACIÓN, MARGEN IZQUIERDO DE LA AVENIDA NAPO, PIEDRA GRANDE, CAPOA, , SAN VICENTE, SHICAMA, SANTA RITA, MANDURO, SAN MARCOS, BATANCOCHA, YAHUARI, RUMIPAMBA, RETEN, LA TOTALIDAD DE LAS PARROQUIAS COTUNDO, HATUN SUMACO Y SAN PABLO DE USHPAYACU, ATACAPI, PLANTA DE AGUA POTABLE COLONSO DEL GAD MUNICIPAL DE TENA, UNIVERSIDAD IKIAM", "cantones": ["ARCHIDONA"], "distribuidora": "Ministerio de Ambiente y Energía"}, {"provincia": "NAPO", "canton": "TENA", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "REEMPLAZO DE CONDUCTOR Y ESTRUCTURAS", "zona_cortes": "CANTÓN TENA-PARROQUIA TENA", "sectores": "BARRIOS: PLAN DE SALUD, ELOY ALFARO, SAN JORGE, LAS GUAYUSAS, PALANDACOCHA, GIL RAMÍREZ DÁVALOS, EL PARAÍSO, SAN LUCAS, HUERTOS FAMILIARES 2, SAN PEDRO DE APAYACU, LAS MALVINAS, GUINEA CHIMBANA, LA TOTALIDAD DE LAS PARROQUIAS PANO Y TALAG.", "cantones": ["TENA"], "distribuidora": "Ministerio de Ambiente y Energía"}, {"provincia": "NAPO", "canton": "TENA", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "REEMPLAZO DE SECCIONADORES Y TRANSFORMADOR", "zona_cortes": "CANTÓN TENA-PARROQUIA TENA", "sectores": "MARGEN DERECHO DE LA VÍA TENA - ARCHIDONA SECTORES 21 DE ENERO, AVATE, SANTA INES MARGEN IZQUIERDO, SECAP, LOS PINOS, AGENCIA NACIONAL DE TRÁNSITO, UGLOPAMBA, SAN LUIS ALTO, DOS RÍOS, TERERE, EL DORADO, PAUSHIYACU BAJO, BELLAVISTA ALTA Y BAJA.", "cantones": ["TENA"], "distribuidora": "Ministerio de Ambiente y Energía"}, {"provincia": "TUNGURAHUA", "canton": "PELILEO", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "REEMPLAZO POSTE EN MAL ESTADO", "zona_cortes": "CANTÓN PELILEO", "sectores": "REDONDEL DE LA HUAMBALEÑA", "cantones": ["PELILEO"], "distribuidora": "Ministerio de Ambiente y Energía"}, {"provincia": "TUNGURAHUA", "canton": "PELILEO", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "REEMPLAZO POSTE EN MAL ESTADO", "zona_cortes": "CANTÓN PELILEO", "sectores": "CALLE PUERTA DEL DORADO VÍA A OLMEDO", "cantones": ["PELILEO"], "distribuidora": "Ministerio de Ambiente y Energía"}, {"provincia": "TUNGURAHUA", "canton": "PELILEO-PATATE", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "CORRECCIÓN DE PUNTOS CALIENTES EN BARRAS 69 Y 13.8 KV DE LA SUBESTACIÓN PELILEO, ACORDE A INFORME DE TERMOGRAFÍA", "zona_cortes": "CANTONES PELILEO Y PATATE", "sectores": "AV. CONFRATERNIDAD, AV. JORGE CHACÓN, EL TAMBO. PARROQUIAS: GARCIA MORENO, PELILEO GRANDE, HUAMBALÓ, COTALÓ, BOLÍVAR DEL CANTÓN PELILEO, Y EL CANTÓN PATATE.", "cantones": ["PELILEO", "PATATE"], "distribuidora": "Ministerio de Ambiente y Energía"}]

=== PalaciosDigital/scraper-cortes-luz/data/vigilancia/registros/4e3a97b5900725cb4abffbacfe981d11e96ffeee619a1884c29e07221d9e4f9a.json
[{"provincia": "LOJA", "canton": "Celica", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "MANTENIMIENTO PREVENTIVO POREL FENÓMENO DEL NIÑO 2026", "zona_cortes": "CELICA", "sectores": "CANTÓN CELICA Sábado, 17 de octubre de", "cantones": ["Celica"], "distribuidora": "Ministerio de Ambiente y Energía"}, {"provincia": "LOJA", "canton": "PINDAL / PUYANGO", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "MANTENIMIENTO PREVENTIVO POR EL FENÓMENO DEL NIÑO", "zona_cortes": "PINDAL / PUYANGO", "sectores": "CANTONES: PINDAL / PUYANGO / ZAPOTILLO", "cantones": ["PINDAL", "PUYANGO"], "distribuidora": "Ministerio de Ambiente y Energía"}, {"provincia": "ZAMORA CHINCHIPE", "canton": "Yantzaza", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "MANTENIMIENTO EMERGENTE 7 DE OPERACIÓN 2026", "zona_cortes": "YANTZAZA ZAMORA CHINCHIPE", "sectores": "SECTOR NORTE DEL ÁREA URBANA DE LA CIUDAD DE VANTZAZA Sábado, 17 de octubre de", "cantones": ["Yantzaza"], "distribuidora": "Ministerio de Ambiente y Energía"}, {"provincia": "ZAMORA CHINCHIPE", "canton": "Yantzaza / Paquisha", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "MANTENIMIENTO EMERGENTE DE OPERACIÓN AA", "zona_cortes": "YANTZAZA / PAQUISHA", "sectores": "PARROQUIA LOS ENCUENTROS Y CHICAÑA DEL CANTÓN YANTZAZA / PARROQUIA BELLAVISTA DEL CANTÓN PAQUISHA", "cantones": ["Yantzaza", "Paquisha"], "distribuidora": "Ministerio de Ambiente y Energía"}, {"provincia": "ZAMORA CHINCHIPE", "canton": "Zamora", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "MANTENIMIENTO EMERGENTE DE OPERACIÓN 2026", "zona_cortes": "ZAMORA ZAMORA CHINCHIPE", "sectores": "PARROQUIA SABANILLA / EL LIMÓN Y ÁREA URBANA DE LA CIUDAD DE ZAMORA Sábado, 17 de octubre de", "cantones": ["Zamora"], "distribuidora": "Ministerio de Ambiente y Energía"}, {"provincia": "ZAMORA CHINCHIPE", "canton": "Zamora", "alimentador": "", "fecha": "2026-10-17", "dia": "Sábado", "horario": "03:00 a 06:00", "tipo_trabajo": "MANTENIMIENTO OPERACIÓN EMERGENTE DE 2026", "zona_cortes": "ZAMORA", "sectores": "/ PARROQUIA CUMBARATZA TIMBARA Y ÁREA URBANA DE LA CIUDAD DE ZAMORA Sábado, 17 de octubre de", "cantones": ["Zamora"], "distribuidora": "Ministerio de Ambiente y Energía"}]
